<a href="https://colab.research.google.com/github/CSheppardCodes/PythonDataScienceHandbook/blob/main/PythonDSH1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##SECTION 1 IPYTHON

enter ! to type terminal commands in Ipython

In [ ]:
directory = !pwd

print(directory[0])
type(directory)

/content


IPython.utils.text.SList

?? shows python code used to create function
%xmode adjusts error message modality

In [ ]:
list??
%xmode verbose

Exception reporting mode: Verbose


In [ ]:
%automagic # 



Automagic is ON, % prefix IS NOT needed for line magics.


In [ ]:
ls# error to test %xmode error message, toggle automagic for ls command to work.

sample_data/


##SECTION 2 INTRO TO NUMPY

In [ ]:
import numpy as np
np.__version__

'1.22.4'

In [ ]:
np?


#Creating Arrays from Scratch

In [ ]:
np.zeros(10, dtype=int) #length 10 int array filled with zeros

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
np.ones((3,5), dtype=float)#3x5 matrix filled with ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.full((3,5), 3.14) # ((rows, col), fillwith)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [ ]:
np.arange(0,20,2)#(from, to, stepsize)


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
np.linspace(0,1,5)#5 values evenly from 0 to 1

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
np.random.random((3,4))#3x4 array uniformly distributed random floats between 0 and 1

array([[0.43785481, 0.71083274, 0.99692951, 0.20564521],
       [0.05922672, 0.9171189 , 0.75315821, 0.5785332 ],
       [0.86223612, 0.46299481, 0.16154563, 0.79173144]])

In [ ]:
np.random.normal(0,1,(3,4))#3x4 normally distributed random, (mean, standard dev, (row, col|))

array([[-0.93070574,  0.76232795, -0.20243874,  1.40511864],
       [ 0.8674715 ,  1.90694543, -1.96928417, -1.79791376],
       [ 0.30540342, -0.58468524,  0.01574332,  1.40758966]])

In [ ]:
np.random.randint(0,10,(3,4)) # 3x4 rand ints from [0, 10)

array([[4, 4, 7, 5],
       [2, 1, 5, 2],
       [7, 0, 4, 6]])

In [ ]:
np.eye(3,3, dtype='bool') #3x3 identity

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

Freestyle

In [ ]:
np.empty(5)#unitialized ?really weird, values are what happens to already exist in that memory location

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
np.random.randint(0,10,(3))

array([0, 9, 7])

In [ ]:
np.eye(1,3,dtype='uint8')

array([[1, 0, 0]], dtype=uint8)

##Basics of Numerical Python Arrays


*   Attributes of arrays: Determining the size, shape, memory consumption, and data types of arrays
*   Indexing of arrays: Getting and setting the value of individual array elements
*   Slicing of arrays: Getting and setting smaller subarrays within a larger array
*   Reshaping of arrays: Changing the shape of a given array
*   Joining and splitting of arrays: Combining multiple arrays into one, and splitting one array into many



#1. Attributes of arrays: Determining the size, shape, memory consumption, and data types of arrays

In [ ]:
import numpy as np
np.random.seed(0) #reproduce random


x1 = np.random.randint(10, size = 6)
x2 = np.random.randint(10, size = (3,4))
x3 = np.random.randint(10, size = (3,4,5))

In [ ]:
print("x3 ndim: ", x3.ndim)     #number of dimensions
print("x3 shape: ", x3.shape)   #size of each dimension
print("x3 size: ", x3.size)     #total size of array

x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60


In [ ]:
print('dtype:', x3.dtype)


dtype: int64


In [ ]:
x1[0]

5

In [ ]:
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [ ]:
x3[0,2,1]= 0.9999#truncate
x3[0,2,1]

0

#2. Array Slicing: Accessing Subarrays

In [ ]:
#x[start:stop:step] default = start=0, stop=size of dimension, step=1
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x[:5]#first 5 elements

array([0, 1, 2, 3, 4])

In [ ]:
x[::-1]#all elements reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

Multi-dimensional sub-arrays

In [ ]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [ ]:
x2[1:3,1:3]#[start,stop)

array([[6, 8],
       [6, 7]])

In [ ]:
x2[::2,::2]#[[row_start:row_stop:row_step),[col_start:col_stop:col_step)]

array([[3, 2],
       [1, 7]])

In [ ]:
x2[::-1,::-1]#revers each dimension

array([[7, 7, 6, 1],
       [8, 8, 6, 7],
       [4, 2, 5, 3]])

In [ ]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [ ]:
print(x2[:,0])#print first column 
              #i.e. access all rows but only first column

[3 7 1]


In [ ]:
print(x2[0,:])#print first row 
              #i.e. access all columns but only first row

[3 5 2 4]


#Subarrays as no-copy views
array slices return views rather than copies of the array data.

In [ ]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [ ]:
x2_sub = x2[:2,:2]
print(x2_sub)

[[99  5]
 [ 7  6]]


In [ ]:
x2_sub[0,0] = 100
print(x2_sub)

[[100   5]
 [  7   6]]


In [ ]:
print(x2)#original array is changed, x2_sub is a veiw not a copy

[[100   5   2   4]
 [  7   6   8   8]
 [  1   6   7   7]]


copy

In [ ]:
x2_sub_copy = x2[:2,:2].copy()
print(x2_sub_copy)

[[100   5]
 [  7   6]]


In [ ]:
x2_sub_copy[0,0] = 42
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


In [ ]:
print(x2)#not modified because .copy()

[[100   5   2   4]
 [  7   6   8   8]
 [  1   6   7   7]]


##reshaping arrays

In [ ]:
grid = np.arange(1,10).reshape((3,3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
