<a href="https://colab.research.google.com/github/CSheppardCodes/PythonDataScienceHandbook/blob/main/PythonDSH1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##SECTION 1 IPYTHON

enter ! to type terminal commands in Ipython

In [ ]:
directory = !pwd

print(directory[0])
type(directory)

/content


IPython.utils.text.SList

?? shows python code used to create function
%xmode adjusts error message modality

In [ ]:
list??
%xmode verbose

Exception reporting mode: Verbose


In [ ]:
%automagic # 



Automagic is OFF, % prefix IS needed for line magics.


In [ ]:
ls# error to test %xmode error message, toggle automagic for ls command to work.

NameError: ignored

##SECTION 2 INTRO TO NUMPY

In [ ]:
import numpy as np
np.__version__

'1.22.4'

In [ ]:
np?


#Creating Arrays from Scratch

In [6]:
np.zeros(10, dtype=int) #length 10 int array filled with zeros

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
np.ones((3,5), dtype=float)#3x5 matrix filled with ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
np.full((3,5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])