<a href="https://colab.research.google.com/github/CSheppardCodes/PythonDataScienceHandbook/blob/main/PythonDSH1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##SECTION 1 IPYTHON

enter ! to type terminal commands in Ipython

In [68]:
directory = !pwd

print(directory[0])
type(directory)

/content


IPython.utils.text.SList

?? shows python code used to create function
%xmode adjusts error message modality

In [69]:
list??
%xmode verbose

Exception reporting mode: Verbose


In [70]:
%automagic # 



Automagic is ON, % prefix IS NOT needed for line magics.


In [71]:
ls# error to test %xmode error message, toggle automagic for ls command to work.

sample_data/


##SECTION 2 INTRO TO NUMPY

In [72]:
import numpy as np
np.__version__

'1.22.4'

In [73]:
np?


#Creating Arrays from Scratch

In [74]:
np.zeros(10, dtype=int) #length 10 int array filled with zeros

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [75]:
np.ones((3,5), dtype=float)#3x5 matrix filled with ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [76]:
np.full((3,5), 3.14) # ((rows, col), fillwith)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [77]:
np.arange(0,20,2)#(from, to, stepsize)


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [78]:
np.linspace(0,1,5)#5 values evenly from 0 to 1

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [79]:
np.random.random((3,4))#3x4 array uniformly distributed random floats between 0 and 1

array([[0.43785481, 0.71083274, 0.99692951, 0.20564521],
       [0.05922672, 0.9171189 , 0.75315821, 0.5785332 ],
       [0.86223612, 0.46299481, 0.16154563, 0.79173144]])

In [80]:
np.random.normal(0,1,(3,4))#3x4 normally distributed random, (mean, standard dev, (row, col|))

array([[-0.93070574,  0.76232795, -0.20243874,  1.40511864],
       [ 0.8674715 ,  1.90694543, -1.96928417, -1.79791376],
       [ 0.30540342, -0.58468524,  0.01574332,  1.40758966]])

In [81]:
np.random.randint(0,10,(3,4)) # 3x4 rand ints from [0, 10)

array([[4, 4, 7, 5],
       [2, 1, 5, 2],
       [7, 0, 4, 6]])

In [82]:
np.eye(3,3, dtype='bool') #3x3 identity

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

Freestyle

In [83]:
np.empty(5)#unitialized ?really weird, values are what happens to already exist in that memory location

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [84]:
np.random.randint(0,10,(3))

array([0, 9, 7])

In [85]:
np.eye(1,3,dtype='uint8')

array([[1, 0, 0]], dtype=uint8)

##Basics of Numerical Python Arrays